<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f8159f1b-48b3-4388-9e2a-ca5fdd520532</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TeamSamsara.Modules.Identity\TeamSamsara.Modules.Identity.csproj" />
    <ProjectReference Include="..\TeamSamsara.Modules.Content\TeamSamsara.Modules.Content.csproj" />
    <ProjectReference Include="..\TeamSamsara.Modules.Media\TeamSamsara.Modules.Media.csproj" />
    <ProjectReference Include="..\TeamSamsara.Modules.Catalog\TeamSamsara.Modules.Catalog.csproj" />
    <ProjectReference Include="..\TeamSamsara.Modules.Orders\TeamSamsara.Modules.Orders.csproj" />
    <ProjectReference Include="..\TeamSamsara.Shared\TeamSamsara.Shared.csproj" />
    <ProjectReference Include="..\TeamSamsara.Modules.PingPong\TeamSamsara.Modules.PingPong.csproj" />
    <ProjectReference Include="..\TeamSamsara.Modules.Assets\TeamSamsara.Modules.Assets.csproj" />
  </ItemGroup>

</Project>
