<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TeamSamsara.Modules.Identity\TeamSamsara.Modules.Identity.csproj" />
    <ProjectReference Include="..\TeamSamsara.Modules.Content\TeamSamsara.Modules.Content.csproj" />
    <ProjectReference Include="..\TeamSamsara.Modules.Media\TeamSamsara.Modules.Media.csproj" />
    <ProjectReference Include="..\TeamSamsara.Modules.Catalog\TeamSamsara.Modules.Catalog.csproj" />
    <ProjectReference Include="..\TeamSamsara.Modules.Orders\TeamSamsara.Modules.Orders.csproj" />
    <ProjectReference Include="..\TeamSamsara.Modules.PingPong\TeamSamsara.Modules.PingPong.csproj" />
  </ItemGroup>

</Project>
